id: DF36F8282
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:44:28+00:00'
last_modified: '2022-05-26T07:47:05.901378+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a3f4:
      image_group_id: I1PD95850
      title: ''
      total_pages: 2069
      order: 5
      base_file: a3f4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
