id: 762d40a380b34938881b9fdceed53b0f
initial_creation_type: ocr
source_metadata:
  volumes:
    36f697dbda764c28be848193b4991c1b:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: ''
      total_pages: 2069
      volume_number: 5
